add page for the official canto dex
neobase-one/vfat-tools pull request #2
Opened 2022-10-27 21:55 UTC by tushar994

2022-10-27 22:29 UTC, akshatcx requested changes

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto.js
> +      ["Canto         ","", `<a href='canto'         >Various</a>`,"CANTO            ","                          "]
Rename to `Canto Dex`

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +
rename file to `canto_dex.js`

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +    const CANTO_FACTORY_ABI = [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"token0","type":"address"
rename `CANTO_FACTORY` to `BaseV1Factory` and similar

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +       const rewardTokenTicker = "  ";
put `wCANTO` here

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +            var CANTO_ROUTER = new ethers.Contract("0xa252eee9bde830ca4793f054b506587027825a8e", CANTO_ROUTER_ABI, App.provider)
move outside

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +            var tokenPrice = tokenPrice/(10**18); // made it 18, as for every case it will be (18 - 18) + 18
get this value from decimals defined above

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +            const apr = borrowRate*blocksPerYear/(10**18);
change `apr` to `dist apr`

2022-10-27 22:29 UTC, akshatcx commented on src/static/js/canto_canto.js
> +    const pairAddresses = [
get pair addresses from `CTOKEN_CONTRACT.underlying()`

2022-10-28 13:30 UTC, SiddarthVijay commented on src/static/js/canto.js
> +      ["Canto         ","", `<a href='canto'         >Various</a>`,"CANTO            ","                          "]
Done

2022-10-28 13:30 UTC, 0xtemujin commented on src/static/js/canto_canto.js
> +
Done

2022-11-02 17:02 UTC, closed without merging